#!/bin/bash
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2014  Marek Marczykowski-Górecki <marmarek@invisiblethingslab.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#

if [ -z "$QUBES_GPG_DOMAIN" ]; then
    echo "ERROR: Destination domain not defined! Set it with QUBES_GPG_DOMAIN env variable." >&2
    exit 1 
fi

if [ $# -gt 0 ]; then
    exec /usr/lib/qubes/qrexec-client-vm $QUBES_GPG_DOMAIN qubes.GpgImportKey /bin/cat "$@"
else
    exec /usr/lib/qubes/qrexec-client-vm $QUBES_GPG_DOMAIN qubes.GpgImportKey /bin/sh -c 'cat /proc/self/fd/$SAVED_FD_0'
fi
